name: Build and Push to ACR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: nataliaragacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Frontend
        run: |
          docker build -t nataliaragacr.azurecr.io/rag-app:v3 -f app/Dockerfile .
          docker push nataliaragacr.azurecr.io/rag-app:v3

      - name: Build and Push Backend
        run: |
          docker build -t nataliaragacr.azurecr.io/rag-faiss:v3 -f faiss/Dockerfile.faiss .
          docker push nataliaragacr.azurecr.io/rag-faiss:v3