FROM python:3.11-slim

WORKDIR /faiss

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY faiss_index/ ./faiss_index
COPY faiss_server.py ./

EXPOSE 8001

CMD ["uvicorn", "faiss_server:app", "--host", "0.0.0.0", "--port", "8001"]


